colls_loader_cls: !!python/name:loader.RecordDirLoader

_proxy_path: &proxyhostport localhost:9002

verify_ssl: false

proxyhostport: *proxyhostport
index_paths: 'redis://127.0.0.1:6379/1'

cookie_scope: root
rewrite_opts:
    rewrite_base: true
    rewrite_rel_canon: false

enable_cdx_api: true

framed_replay: inverse

enable_auto_colls: true

metadata:
    org: National Football Musesum
