#colls_loader_cls: !!python/name:loader.AccountUserLoader
_proxy_path: &proxyhostport localhost:9002

verify_ssl: false

collections:
    #'^([\w]+)/([\w][-\w]+)/record':
    record:
        index_paths: $liveweb

        wb_handler_class: !!python/name:loader.DynRecord

        proxyhostport: *proxyhostport

        cookie_scope: root
        rewrite_opts:
            rewrite_base: true
            rewrite_rel_canon: false

    #'^([\w]+)/([\w][-\w]+)(?!/record)':
    '':
        #index_paths: indexes/index.cdxj
        index_paths: 'redis://127.0.0.1:6379/1'
        server_cls: !!python/name:loader.DynCDXServer

        wb_handler_class: !!python/name:loader.DynWBHandler

        enable_cdx_api: true

route_class: !!python/name:loader.DynamicRoute

archive_paths: ./

#framed_replay: false
framed_replay: inverse

#enable_auto_colls: true
