#colls_loader_cls: !!python/name:loader.AccountUserLoader
proxy_path: &proxyhostport localhost:9002
#redis_url: &redis_url redis://127.0.0.1:6379/1
redis_url: &redis_url redis://redacted

s3_target: s3://redacted

cookie_name: '__wr_sesh'

verify_ssl: false

multiuser: true

warcsign_private_key: /var/wr/wr.pem
warcsign_public_key: /var/wr/wr_pub.pem

#enable_auto_colls: false
collections_root: _na_

collections:
    'live':
        index_paths: $liveweb

        wb_handler_class: !!python/name:loader.DynRecord

        cookie_scope: default
        rewrite_opts:
            rewrite_base: true
            rewrite_rel_canon: false

        search_html: frame_insert.html

    'record':
        index_paths: $liveweb

        wb_handler_class: !!python/name:loader.DynRecord

        proxyhostport: *proxyhostport

        cookie_scope: default
        rewrite_opts:
            rewrite_base: true
            rewrite_rel_canon: false

        search_html: frame_insert.html

    'patch':
        index_paths: *redis_url
        server_cls: !!python/name:loader.DynCDXServer

        wb_handler_class: !!python/name:loader.DynWBHandler

        cookie_scope: removeall

        fallback: record

        search_html: frame_insert.html
    
    '':
        #index_paths: indexes/index.cdxj
        index_paths: *redis_url
        server_cls: !!python/name:loader.DynCDXServer

        wb_handler_class: !!python/name:loader.DynWBHandler

        cookie_scope: removeall

        enable_cdx_api: 'cdx'


route_class: !!python/name:loader.DynamicRoute

archive_paths: ./

metadata:
    org: beta.webrecorder.io
    product: beta.webrecorder.io
#    org: National Football Museum Web Archive
#    product: NFM Web Archive

framed_replay: inverse
#framed_replay: false
#urlrewriter_class: !!python/name:loader.DynUrlRewriter
