#colls_loader_cls: !!python/name:loader.AccountUserLoader
_proxy_path: &proxyhostport localhost:9002
redis_url: &redis_url redis://127.0.0.1:6379/1

verify_ssl: false

multiuser: true

#enable_auto_colls: false
collections_root: _na_

collections:
    record:
        index_paths: $liveweb

        wb_handler_class: !!python/name:loader.DynRecord

        proxyhostport: *proxyhostport

        cookie_scope: root
        rewrite_opts:
            rewrite_base: true
            rewrite_rel_canon: false

    '':
        #index_paths: indexes/index.cdxj
        index_paths: *redis_url
        server_cls: !!python/name:loader.DynCDXServer

        wb_handler_class: !!python/name:loader.DynWBHandler

        enable_cdx_api: 'cdx'

route_class: !!python/name:loader.DynamicRoute

archive_paths: ./

metadata:
    org: webrecorder.io
    product: webrecorder.io
#    org: National Football Museum Web Archive
#    product: NFM Web Archive

#framed_replay: inverse
framed_replay: false
#urlrewriter_class: !!python/name:loader.DynUrlRewriter
