version: '2'

services:
    app:
        build: ./webrecorder
        env_file:
            - ./wr.env
            - ./webrecorder/webrecorder.env

        links:
            - webagg
            - recorder

        ports:
            - 8080:8080

        volumes:
            - ./webrecorder/:/code/

    nginx:
        build: ./nginx
        ports:
            - "8089:80"

        #volumes:
        #    - ./app/:/app/

        volumes_from:
            - app

        links:
            - app

    recorder:
        build: ./rec
        env_file:
            - ./wr.env

        links:
            - webagg
            - redis

        volumes:
            - ./rec/:/rec/

        volumes_from:
            - data


    webagg:
        build: ./webagg
        env_file:
            - ./wr.env

        links:
            - redis

        volumes_from:
            - data


    redis:
        build: ./redis

        ports:
            - "6379:6379"
  
        volumes_from:
            - data

        env_file:
            - ./webrecorder/webrecorder.env

    # Postfix (if sending mail locally)
    mailserver:
        restart: always
        image: catatnight/postfix

        environment:
            - "maildomain=mail.webrecorder.io"
            - "smtp_user=webrec:archive"


    # Data Only Volume
    data:
      image: python:3.5

      command: python -i
      
      volumes:
        - ./data:/data
        - ./wr.yaml:/wr.yaml


