version: '2'

services:
    app:
        build: ./webrecorder
        env_file:
            - ./wr.env
            - ./webrecorder/webrecorder.env

        depends_on:
            - webagg
            - recorder

        ports:
            - 8080:8080

        volumes:
            - ./webrecorder/:/code/

    nginx:
        build: ./nginx
        ports:
            - "8089:80"

        #volumes:
        #    - ./app/:/app/

        volumes_from:
            - app
            - browsermanager

        depends_on:
            - app

    recorder:
        build: ./rec
        env_file:
            - ./wr.env

        depends_on:
            - webagg
            - redis

        volumes:
            - ./rec/:/rec/

        volumes_from:
            - data


    webagg:
        build: ./webagg
        env_file:
            - ./wr.env

        depends_on:
            - redis

        volumes_from:
            - data


    browsermanager:
        image: webrecorder/browsermanager

        ports:
            - 9020:9020

        env_file:
            - ./wr.env
 
        environment:
            - STATIC_PATH=/static/__bp
            - SCREEN_WIDTH=1280
            - SCREEN_HEIGHT=800

        depends_on:
            - redis

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./browser/browser_app.py:/app/browser_app.py
            - ./browser/run_browser:/usr/bin/run_browser
            - /dev/shm:/dev/shm

    proxy:
        image: webrecorder/proxy

        depends_on:
            - redis

        env_file:
            - ./wr.env

        command: mitmdump -p 8080 --client-certs /certs/ --no-http2 -s "/code/run.py --host http://webagg:8080/ --redis redis://redis:6379/0"
 

    redis:
        build: ./redis

        ports:
            - "6379:6379"
  
        volumes_from:
            - data

        env_file:
            - ./webrecorder/webrecorder.env

    # Postfix (if sending mail locally)
    mailserver:
        restart: always
        image: catatnight/postfix

        environment:
            - "maildomain=mail.webrecorder.io"
            - "smtp_user=webrec:archive"


    # Data Only Volume
    data:
      image: python:3.5

      command: python -i
      
      volumes:
        - ./data:/data
        - ./wr.yaml:/wr.yaml

