version: '2'

services:
    app:
        build: ./webrecorder
        command: uwsgi /code/apps/frontend.ini

        env_file:
            - ./wr.env

        depends_on:
            - webagg
            - recorder
            - redis

        volumes:
            - ./webrecorder/:/code/
            - ./wr.yaml:/wr.yaml

        ports:
            - 8080:8080

    recorder:
        build: ./webrecorder
        command: uwsgi /code/apps/rec.ini

        env_file:
            - ./wr.env

        depends_on:
            - webagg
            - redis

        volumes:
            - ./webrecorder/:/code/

        volumes_from:
            - data

    webagg:
        build: ./webrecorder
        command: uwsgi /code/apps/load.ini

        env_file:
            - ./wr.env

        depends_on:
            - redis

        volumes:
            - ./webrecorder/:/code/

        volumes_from:
            - data


    nginx:
        build: ./nginx
        ports:
            - "8089:80"

        depends_on:
            - app

        volumes_from:
            - app
            - browsermanager
            - data

    browsermanager:
        build: ./browsermanager

        #ports:
        #    - 9020:9020

        env_file:
            - ./wr.env
 
        environment:
            - STATIC_PATH=/static/__bp
            - SCREEN_WIDTH=1280
            - SCREEN_HEIGHT=800

        depends_on:
            - redis

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./browsermanager/browser_app.py:/app/browser_app.py
            - ./browsermanager/run_browser:/usr/bin/run_browser
            - ./browsermanager/webrec.pem:/home/browser/self.pem
            - ./browsermanager/launch.sh:/novnc/utils/launch.sh
            - /dev/shm:/dev/shm

    proxy:
        build: ./proxy

        env_file:
            - ./wr.env

        depends_on:
            - redis

        volumes:
            - ./proxy/certs:/home/apprun/.mitmproxy

    redis:
        build: ./redis

        env_file:
            - ./wr.env

        ports:
            - "6379:6379"
  
        volumes_from:
            - data

    # Postfix (if sending mail locally)
    mailserver:
        restart: always
        image: catatnight/postfix

        environment:
            - "maildomain=localhost"
            - "smtp_user=test:archive"


    # Data Only Volume
    data:
      image: python:3.5.2

      command: python -i
      
      volumes:
        - ./data:/data
        - ./wr.yaml:/wr.yaml

