version: '2'

services:
    app:
        build: ./webrecorder
        environment:
            - RECORD_HOST=http://recorder:8010
            - REPLAY_HOST=http://webagg:8080

        env_file:
            - ./webrecorder/webrecorder.env

        links:
            - webagg
            - recorder

        ports:
            - 8080:8080

        volumes:
            - ./webrecorder/:/code/

    nginx:
        build: ./nginx
        ports:
            - "8089:80"

        #volumes:
        #    - ./app/:/app/

        volumes_from:
            - app

        links:
            - app

    recorder:
        build: ./rec
        environment:
            - UPSREAM_HOST=http://webagg:8080
            - RECORD_ROOT=/data/
            - REDIS_BASE_URL=redis://redis:6379/1/

        links:
            - webagg
            - redis

        volumes:
            - ./rec/:/rec/

        volumes_from:
            - data


    webagg:
        build: ./webagg
        environment:
            - REDIS_BASE_URL=redis://redis:6379/1/

        links:
            - redis

        volumes_from:
            - data


    redis:
        image: redis:2.8.21


    # Postfix (if sending mail locally)
    mailserver:
        restart: always
        image: catatnight/postfix

        environment:
            - "maildomain=mail.webrecorder.io"
            - "smtp_user=webrec:archive"


    # Data Only Volume
    data:
      image: python:3.5

      command: python -i
      
      volumes:
        - ./warcdata:/data


