version: '2'

services:
    app:
        build: ./app

        links:
            - webagg
            - recorder

        ports:
            - 8080:8080

        volumes:
            - ./app/:/app/

    recorder:
        build: ./recorder
        environment:
            - UPSREAM_HOST=http://webagg:8080
            - RECORD_ROOT=/data/
            - REDIS_BASE_URL=redis://redis:6379/1/

        links:
            - webagg
            - redis

        volumes_from:
            - data


    webagg:
        build: ./webagg
        environment:
            - REDIS_BASE_URL=redis://redis:6379/1/

        links:
            - redis

        volumes_from:
            - data


    redis:
        image: redis:2.8.21


    # Data Only Volume
    data:
      image: python:3.5

      command: python -i
      
      volumes:
        - ./warcdata:/data


