# Redis
redis:
  restart: always
  #image: redis:latest
  build: ./redis
  ports:
    - "6379:6379"
  
  volumes_from:
    - data

  env_file:
    - ./webrecorder/webrecorder.env

 # command: redis-server --appendonly yes

# Data Only Volume
data:
  #restart: always

  image: python:2.7

  command: python -i
  
  volumes:
    - ./data:/data/
    - ./webrecorder/static:/code/static/

# Warcprox
warcprox:
  restart: always
  build: ./warcprox

  command: ./run-rec.sh

  volumes_from:
    - data

  links:
    - redis

  environment:
    - DATA=/data/

  ports:
    - "9002:9002"

  env_file:
    - ./webrecorder/webrecorder.env





# Webrecorder
webrecorder:
  restart: always
  build: ./webrecorder

  command: uwsgi uwsgi.ini

  volumes_from:
    - data

  links:
    - redis
    - warcprox

  env_file:
    - ./webrecorder/webrecorder.env

  #ports:
  #  - "8088:8088"

nginx:
  build: ./nginx
  ports:
    - "8089:80"

  volumes_from:
    - data

  links:
    - webrecorder

