query_html: time_info.html

redis_url: &redis_url $REDIS

session_opts:
    session.secret: $SECRET_KEY
    session.encrypt_key: $ENCRYPT_KEY
    session.validate_key: $VALIDATE_KEY

    session.auto: false
    session.cookie_expires: True

    session.httponly: true
    session.cookie_path: '/'
    
    session.key: __wr_sesh
    session.type: redis

    session.url: *redis_url

    session.expire: 5400


anon_duration: 5400

default_max_size: 100000000
default_max_anon_size: 500000000
default_max_coll: 10

invites_enabled: $REQUIRE_INVITES

warcsign_private_key: ./keys/wr.pem
warcsign_public_key: ./keys/wr_pub.pem

email_sender: $EMAIL_SENDER
email_smtp_url: $EMAIL_SMTP_URL

store_root: /data/

metadata:
    org: webrecorder.io
    product: webrecorder.io

framed_replay: inverse

