#colls_loader_cls: !!python/name:loader.AccountUserLoader
proxy_path: &proxyhostport warcprox_1:9002
#redis_url: &redis_url redis://127.0.0.1:6379/1
#redis_url: &redis_url redis://localhost:6379/1
#proxy_path: &proxyhostport $WARCPROX
redis_url: &redis_url $REDIS

#s3_target: s3://target-bucket-path/
s3_target: $S3_ROOT
proxy_target: ''
#http://localhost:6009/wr-beta/

cookie_name: '__wr_sesh'

verify_ssl: false

multiuser: true

#warcsign_private_key: /var/wr/wr.pem
#warcsign_public_key: /var/wr/wr_pub.pem
warcsign_private_key: /keys/wr.pem
warcsign_public_key: /keys/wr_pub.pem

email_sender: $EMAIL_SENDER
email_smtp_url: $EMAIL_SMTP_URL


#enable_auto_colls: false
collections_root: _na_

collections:
    'live':
        index_paths: $liveweb

        wb_handler_class: !!python/name:loader.DynRecord

        cookie_scope: root
        rewrite_opts:
            rewrite_base: true
            rewrite_rel_canon: false

        search_html: frame_insert.html

    'record':
        index_paths: $liveweb

        wb_handler_class: !!python/name:loader.DynRecord

        proxyhostport: *proxyhostport

        cookie_scope: root
        rewrite_opts:
            rewrite_base: true
            rewrite_rel_canon: false

        search_html: frame_insert.html

    'patch':
        index_paths: *redis_url
        server_cls: !!python/name:loader.DynCDXServer

        wb_handler_class: !!python/name:loader.DynWBHandler

        cookie_scope: root

        fallback: record

        search_html: frame_insert.html
    
    '':
        #index_paths: indexes/index.cdxj
        index_paths: *redis_url
        server_cls: !!python/name:loader.DynCDXServer

        wb_handler_class: !!python/name:loader.DynWBHandler

        cookie_scope: removeall

        enable_cdx_api: 'cdx'


route_class: !!python/name:loader.DynamicRoute

#archive_paths: ./
archive_paths: /
store_root: /data/

metadata:
    org: beta.webrecorder.io
    product: beta.webrecorder.io

framed_replay: inverse
redir_to_exact: false

#urlrewriter_class: !!python/name:loader.DynUrlRewriter
